import { NextRequest } from "next/server";

export async function GET(req: NextRequest) {

    const service = req.nextUrl.searchParams.get("action")
    
    const key = req.nextUrl.searchParams.get("key")
    console.log({service, key});
    const token = "293413dd0682984a5e5665456d95f83140aab34e"
    if (key !== token) {
        return Response.json({
            message: "Invalid key",
        });
    }
    if (service === "services") {
        return Response.json([
            {
                "service": 746,
                "name": "TikTok Views 🎉",
                "type": "Default",
                "category": "TikTok - Views",
                "network": null,
                "description": "",
                "rate": 36.0485,
                "min": 100,
                "max": 2147483647,
                "refill": false,
                "canceling_is_available": true,
                "cancel": true
            },
            {
                "service": 747,
                "name": "TikTok Views | Trending + Viral Views ⚡",
                "type": "Default",
                "category": "TikTok - Views",
                "network": null,
                "description": "✅ These views have different algorithm and help in making the video viral and trending\n✅Benefits of views: You may gain organic likes,followers and video can go viral if the content is good\n\n\n⚠️Note: \n-Please don't order for the same link at the same time. You have to wait for the first order to be completed then you can order again.\n-If you changed your account to private mode or the account/post was deleted your order will be automatically marked as completed and we will not guarantee any refund.",
                "rate": 3304.4417,
                "min": 100,
                "max": 100000000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 748,
                "name": "TikTok Likes + Views [ Worldwide 🌍 ] [ Max 1M ] | 𝗛𝗤+𝗥𝗘𝗔𝗟 | Cancel & Refill Enable | Drop 0% | 30 Days ♻️ | Day 100K ⚡",
                "type": "Default",
                "category": "TikTok - Likes",
                "network": null,
                "description": "",
                "rate": 4506.0569,
                "min": 10,
                "max": 10000000,
                "refill": true,
                "canceling_is_available": true,
                "cancel": true
            },
            {
                "service": 749,
                "name": "TikTok Shares💧",
                "type": "Default",
                "category": "TikTok - Shares",
                "network": null,
                "description": "",
                "rate": 2183.8362,
                "min": 10,
                "max": 10000000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 750,
                "name": "TikTok Live Stream Views + PK Battle Points | 15 Minutes | Global 🌎 | MAX 50K",
                "type": "Default",
                "category": "TikTok - Live Stream Views + PK Battle Points",
                "network": null,
                "description": "",
                "rate": 19408.2307,
                "min": 10,
                "max": 100000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 751,
                "name": "TikTok Live Stream Views + PK Battle Points | 30 Minutes | Global 🌎 | MAX 50K",
                "type": "Default",
                "category": "TikTok - Live Stream Views + PK Battle Points",
                "network": null,
                "description": "",
                "rate": 38470.2318,
                "min": 10,
                "max": 100000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 752,
                "name": "TikTok Live Stream Views + PK Battle Points | 60 Minutes | Global 🌎 | MAX 50K",
                "type": "Default",
                "category": "TikTok - Live Stream Views + PK Battle Points",
                "network": null,
                "description": "",
                "rate": 76645.998,
                "min": 10,
                "max": 100000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 753,
                "name": "TikTok Live Stream Views + PK Battle Points | 90 Minutes | Global 🌎 | MAX 50K",
                "type": "Default",
                "category": "TikTok - Live Stream Views + PK Battle Points",
                "network": null,
                "description": "",
                "rate": 114823.1799,
                "min": 10,
                "max": 100000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 754,
                "name": "TikTok Live Stream Views + PK Battle Points | 120 Minutes | Global 🌎 | MAX 50K",
                "type": "Default",
                "category": "TikTok - Live Stream Views + PK Battle Points",
                "network": null,
                "description": "",
                "rate": 152998.9461,
                "min": 10,
                "max": 100000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 755,
                "name": "TikTok Live Stream Views + PK Battle Points | 180 Minutes | Global 🌎 | MAX 50K",
                "type": "Default",
                "category": "TikTok - Live Stream Views + PK Battle Points",
                "network": null,
                "description": "",
                "rate": 229350.4785,
                "min": 10,
                "max": 100000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 756,
                "name": "TikTok Live Stream Views + PK Battle Points | 240 Minutes | Global 🌎 | MAX 50K",
                "type": "Default",
                "category": "TikTok - Live Stream Views + PK Battle Points",
                "network": null,
                "description": "",
                "rate": 305996.4765,
                "min": 10,
                "max": 100000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 757,
                "name": "TikTok Live Stream Views + PK Battle Points | 360 Minutes | Global 🌎 | MAX 50K",
                "type": "Default",
                "category": "TikTok - Live Stream Views + PK Battle Points",
                "network": null,
                "description": "",
                "rate": 458700.957,
                "min": 10,
                "max": 100000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 758,
                "name": "TikTok PK Battle Points 💧",
                "type": "Default",
                "category": "TikTok - PK Battle Points",
                "network": null,
                "description": "",
                "rate": 5821.3506,
                "min": 100,
                "max": 10000000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 759,
                "name": "TikTok PK Battle Points | No Drop | No Refill",
                "type": "Default",
                "category": "TikTok - PK Battle Points",
                "network": null,
                "description": "",
                "rate": 3604.8455,
                "min": 100,
                "max": 217545811,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 760,
                "name": "TikTok - Comment ~ Emoji ~ 𝗥30 ~ 🚀 📣",
                "type": "Default",
                "category": "TikTok - Comments",
                "network": null,
                "description": "",
                "rate": 108628.1568,
                "min": 10,
                "max": 100000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 761,
                "name": "🇺🇸TikTok Views [United States]",
                "type": "Default",
                "category": "TikTok - Views Targeted",
                "network": null,
                "description": "⚠️Note:\n📌Check the link format carefully before placing the order.\n📌Kindly make sure your account is public, not private.\n📌When the service is busy, the starting speed of the operation changes.\n📌Do not change your post link, username, or account setting (private/public) after ordering\n📌If you changed your account to private mode or the account/post was deleted your order will be automatically marked as completed and we will not guarantee any refund.",
                "rate": 361.79,
                "min": 50,
                "max": 50000000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 762,
                "name": "🇲🇾TikTok Views [Malaysia]",
                "type": "Default",
                "category": "TikTok - Views Targeted",
                "network": null,
                "description": "⚠️Note:\n📌Check the link format carefully before placing the order.\n📌Kindly make sure your account is public, not private.\n📌When the service is busy, the starting speed of the operation changes.\n📌Do not change your post link, username, or account setting (private/public) after ordering\n📌If you changed your account to private mode or the account/post was deleted your order will be automatically marked as completed and we will not guarantee any refund.",
                "rate": 4598.1936,
                "min": 100,
                "max": 50000000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
            {
                "service": 763,
                "name": "Instagram Old Accounts Likes ⛔♻️🔥📣 🌟",
                "type": "Default",
                "category": "Instagram - Likes",
                "network": null,
                "description": "RB365\n\n⚠️Note:\n📌Check the link format carefully before placing the order.\n📌Kindly make sure your account is public, not private.\n📌When the service is busy, the starting speed of the operation changes.\n📌Do not change your post link, username, or account setting (private/public) after ordering\n📌If you changed your account to private mode or the account/post was deleted your order will be automatically marked as completed and we will not guarantee any refund.",
                "rate": 799.0741,
                "min": 10,
                "max": 300000,
                "refill": false,
                "canceling_is_available": true,
                "cancel": true
            },
            {
                "service": 764,
                "name": "Instagram Likes Indonesia HQ",
                "type": "Default",
                "category": "Instagram - Indonesia Services 🇮🇩",
                "network": null,
                "description": "",
                "rate": 28081.8252,
                "min": 100,
                "max": 50000,
                "refill": false,
                "canceling_is_available": false,
                "cancel": false
            },
        ]);
    }
}